theme: jekyll-theme-minimal
title: Joe Shenouda Github | Click-the-Button
description: Click the Button HTML5 game made for #gamedevjs . I want to highlight that the code I've written is not only shortest in your competition but also entertaining.

